import { Merriweather } from 'next/font/google'
import '../styles/globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const merriweather = Merriweather({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
