export const projects = [
  {
    slug: 'rediseno-web-resistance',
    title: 'Rediseño web',
    subtitle: 'Modernización y optimización para una mejor experiencia',
    client: 'Resistance',
    role: 'Diseño + Dev',
    description:
      'Resistance necesitaba una web más moderna, funcional y alineada con su identidad. Rediseñé la estructura y el diseño para mejorar la accesibilidad, la navegación y la experiencia del usuario. Implementé Next.js y CSS Modules para optimizar el rendimiento, mejorar la organización del contenido y potenciar el posicionamiento SEO. El resultado: un sitio más limpio, rápido y fácil de explorar.',
    en: {
      title:       'Web Redesign',
      subtitle:    'Modernization and optimization for a better experience',
      role:        'Design + Dev',
      description: 'Resistance needed a more modern, functional website aligned with their identity. I redesigned the structure and layout to improve accessibility, navigation and user experience. I implemented Next.js and CSS Modules to optimize performance, improve content organization and enhance SEO positioning. The result: a cleaner, faster and easier-to-navigate site.',
      process: [
        { num: '01', title: 'Research',    desc: 'Analysis of the existing site, competitor benchmarking and user pain point definition.' },
        { num: '02', title: 'UX/UI Design', desc: 'Wireframes, Figma prototyping and information architecture validation with the client.' },
        { num: '03', title: 'Development', desc: 'Implementation with Next.js, performance optimization and deployment on Vercel with CI/CD.' },
      ],
      results: [
        { value: '+40%', label: 'Load speed'         },
        { value: '100',  label: 'Lighthouse score'   },
        { value: 'A11y', label: 'Improved accessibility' },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Next.js',     percentage: 90 },
      { name: 'CSS Modules', percentage: 80 },
      { name: 'Figma',       percentage: 75 },
      { name: 'Vercel',      percentage: 65 },
      { name: 'SEO',         percentage: 70 },
    ],
    process: [
      { num: '01', title: 'Investigación',  desc: 'Análisis del sitio existente, benchmarking de competidores y definición de pain points del usuario.' },
      { num: '02', title: 'Diseño UX/UI',   desc: 'Wireframes, prototipado en Figma y validación de la arquitectura de información con el cliente.' },
      { num: '03', title: 'Desarrollo',     desc: 'Implementación con Next.js, optimización de performance y deploy en Vercel con CI/CD.' },
    ],
    results: [
      { value: '+40%', label: 'Velocidad de carga'       },
      { value: '100',  label: 'Score en Lighthouse'      },
      { value: 'A11y', label: 'Accesibilidad mejorada'   },
    ],
    frontImage: '/projects/ResistanceWeb.png',
    image:      '/projects/ResistanceWeb.png',
    gallery: [
      '/projects/ResistanceWeb.png',
    ],
    url:        'https://resistance.com.co',
    category:   'Website Design',
  },
  {
    slug: 'contenido-redes-resistance',
    title: 'Contenido RRSS',
    subtitle: 'Construyendo presencia digital con impacto',
    client: 'Resistance',
    role: 'Diseño Digital',
    description:
      'Desarrollé contenido visual y estratégico para las redes sociales de Resistance, alineando su identidad con mensajes claros y atractivos. Desde publicaciones informativas hasta material promocional, creé piezas que fortalecieron su imagen y mejoraron el engagement con la audiencia, destacando su experiencia en ciberseguridad.',
    en: {
      title:       'Social Media Content',
      subtitle:    'Building digital presence with impact',
      role:        'Digital Design',
      description: 'I developed visual and strategic content for Resistance\'s social media channels, aligning their identity with clear and attractive messages. From informative posts to promotional material, I created pieces that strengthened their image and improved audience engagement, highlighting their expertise in cybersecurity.',
      process: [
        { num: '01', title: 'Strategy',       desc: 'Audience analysis, brand voice definition and content calendar planning.' },
        { num: '02', title: 'Visual Design',  desc: 'Creation of templates, graphic pieces and promotional material aligned with brand identity.' },
        { num: '03', title: 'Publishing',     desc: 'Scheduling, publication and performance monitoring across social platforms.' },
      ],
      results: [
        { value: '+3x',  label: 'Content output'   },
        { value: '100%', label: 'Brand consistency' },
        { value: '↑ER',  label: 'Engagement rate'  },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Illustrator', percentage: 85 },
      { name: 'Photoshop',   percentage: 75 },
      { name: 'Canva',       percentage: 70 },
      { name: 'Meta Ads',    percentage: 60 },
    ],
    process: [
      { num: '01', title: 'Estrategia',       desc: 'Análisis de audiencia, definición de voz de marca y planificación del calendario de contenidos.' },
      { num: '02', title: 'Diseño visual',    desc: 'Creación de plantillas, piezas gráficas y material promocional alineado con la identidad de marca.' },
      { num: '03', title: 'Publicación',      desc: 'Programación, publicación y seguimiento del rendimiento en cada plataforma.' },
    ],
    results: [
      { value: '+3x',  label: 'Volumen de contenido' },
      { value: '100%', label: 'Coherencia de marca'  },
      { value: '↑ER',  label: 'Engagement rate'      },
    ],
    frontImage: null,
    image:      null,
    gallery:    [],
    url:        '',
    category:   'Social Media',
  },
  {
    slug: 'branding-pequena-venecia',
    title: 'Identidad visual',
    subtitle: 'Un diseño que refleja su esencia',
    client: 'La Pequeña Venecia Bodegón',
    role: 'Diseño Gráfico',
    description:
      'Creé el manual de identidad y branding para La Pequeña Venecia, definiendo la paleta de colores, tipografías y elementos gráficos que transmiten su autenticidad. El resultado es una identidad visual coherente y versátil, diseñada para fortalecer su presencia en distintos medios.',
    en: {
      title:       'Visual Identity',
      subtitle:    'A design that reflects its essence',
      role:        'Graphic Design',
      description: 'I created the identity manual and branding for La Pequeña Venecia, defining the color palette, typography and graphic elements that convey its authenticity. The result is a coherent and versatile visual identity, designed to strengthen its presence across different media.',
      process: [
        { num: '01', title: 'Research',    desc: 'Brand values analysis, competitor research and moodboard creation to define the visual direction.' },
        { num: '02', title: 'Concept',     desc: 'Logo proposals, color palette and typography system aligned with the brand\'s personality.' },
        { num: '03', title: 'Brand Guide', desc: 'Full identity manual with usage rules, variations and application examples across media.' },
      ],
      results: [
        { value: '1',     label: 'Cohesive identity'  },
        { value: '360°',  label: 'Multi-media system' },
        { value: 'v1.0',  label: 'Brand guide'        },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Illustrator',    percentage: 90 },
      { name: 'Figma',          percentage: 70 },
      { name: 'Branding',       percentage: 95 },
      { name: 'Manual de marca', percentage: 85 },
    ],
    process: [
      { num: '01', title: 'Investigación', desc: 'Análisis de valores de marca, investigación de competidores y moodboard para definir la dirección visual.' },
      { num: '02', title: 'Concepto',      desc: 'Propuestas de logotipo, paleta de color y sistema tipográfico alineados con la personalidad de la marca.' },
      { num: '03', title: 'Manual',        desc: 'Manual de identidad completo con reglas de uso, variaciones y ejemplos de aplicación en distintos medios.' },
    ],
    results: [
      { value: '1',    label: 'Identidad cohesiva'   },
      { value: '360°', label: 'Sistema multisoporte' },
      { value: 'v1.0', label: 'Brand guide'          },
    ],
    frontImage: null,
    image:      null,
    gallery:    [],
    url:        '',
    category:   'Branding',
  },
  {
    slug: 'web-vulnmaster',
    title: 'Diseño y frontend',
    subtitle: 'Plataforma de ciberseguridad con IA, diseñada para ser tan clara como potente',
    client: 'Vulnmaster',
    role: 'Diseño + Dev',
    description:
      'Vulnmaster es una plataforma SaaS de análisis de vulnerabilidades impulsada por inteligencia artificial. Diseñé y desarrollé el sitio web completo: desde la arquitectura de información hasta la implementación en Next.js con Tailwind CSS. El reto fue comunicar un producto técnico complejo —escaneos automatizados, matrices de riesgo OWASP, reportes con IA— de forma clara y accesible para equipos de seguridad y clientes no técnicos por igual.',
    en: {
      title:       'Design & Frontend',
      subtitle:    'An AI-powered cybersecurity platform, designed to be as clear as it is powerful',
      role:        'Design + Dev',
      description: 'Vulnmaster is an AI-powered vulnerability analysis SaaS platform. I designed and developed the full website: from information architecture to Next.js implementation with Tailwind CSS. The challenge was communicating a complex technical product —automated scans, OWASP risk matrices, AI-generated reports— in a clear and accessible way for both security teams and non-technical clients.',
      process: [
        { num: '01', title: 'UX Strategy',  desc: 'Audience analysis (security experts vs. non-technical buyers), user flow mapping and Figma prototyping.' },
        { num: '02', title: 'UI & System',  desc: 'Visual system aligned with the cybersecurity brand: dark palette, high contrast, component-based layout with Tailwind CSS.' },
        { num: '03', title: 'Development',  desc: 'Next.js implementation with performance optimization, responsive design and deployment on Vercel.' },
      ],
      results: [
        { value: '100%', label: 'Responsive'      },
        { value: 'A+',   label: 'Performance'     },
        { value: 'Live', label: 'vulnmaster.us'   },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Next.js',      percentage: 90 },
      { name: 'Tailwind CSS', percentage: 85 },
      { name: 'Figma',        percentage: 80 },
      { name: 'Vercel',       percentage: 65 },
      { name: 'SaaS',         percentage: 70 },
    ],
    process: [
      { num: '01', title: 'UX Strategy',   desc: 'Análisis de audiencia (expertos en seguridad vs. compradores no técnicos), mapeo de flujos y prototipado en Figma.' },
      { num: '02', title: 'UI y sistema',  desc: 'Sistema visual alineado con la marca de ciberseguridad: paleta oscura, alto contraste y maquetación por componentes con Tailwind CSS.' },
      { num: '03', title: 'Desarrollo',    desc: 'Implementación en Next.js con optimización de performance, diseño responsive y deploy en Vercel.' },
    ],
    results: [
      { value: '100%', label: 'Responsive'    },
      { value: 'A+',   label: 'Performance'   },
      { value: 'Live', label: 'vulnmaster.us' },
    ],
    frontImage: '/projects/VulnmasterWeb (1).png',
    image:      '/projects/VulnmasterWeb (1).png',
    gallery: [
      '/projects/VulnmasterWeb (1).png',
      '/projects/VulnmasterWeb (2).png',
      '/projects/VulnmasterWeb (3).png',
      '/projects/VulnmasterWeb (4).png',
    ],
    url:        'https://vulnmaster.us',
    category:   'Website Design',
  },
  {
    slug: 'dashboard-vulnmaster',
    title: 'Dashboard interactivo',
    subtitle: 'Convertir datos de seguridad complejos en decisiones claras',
    client: 'Vulnmaster',
    role: 'Diseño + Dev',
    description:
      'Diseñé y desarrollé el dashboard interno de Vulnmaster: la interfaz donde los equipos de seguridad gestionan vulnerabilidades, priorizan riesgos y toman acción. La plataforma centraliza escaneos automáticos con herramientas como Burp Suite, NMAP y OpenVAS, matrices de riesgo basadas en OWASP, recomendaciones generadas por IA y reportes exportables en Excel, PDF y HTML. El reto fue hacer que toda esa densidad de datos fuera legible, accionable y sin fricción.',
    en: {
      title:       'Interactive Dashboard',
      subtitle:    'Turning complex security data into clear decisions',
      role:        'Design + Dev',
      description: 'I designed and developed Vulnmaster\'s internal dashboard: the interface where security teams manage vulnerabilities, prioritize risks and take action. The platform centralizes automated scans from tools like Burp Suite, NMAP and OpenVAS, OWASP-based risk matrices, AI-generated recommendations and exportable reports in Excel, PDF and HTML. The challenge was making all that data density readable, actionable and frictionless.',
      process: [
        { num: '01', title: 'Data Architecture', desc: 'Mapping all data types (scan results, risk levels, action plans, history) and defining hierarchy and grouping logic.' },
        { num: '02', title: 'UI Design',         desc: 'Component design for risk matrices, vulnerability cards and report panels. Interactive prototyping in Figma.' },
        { num: '03', title: 'Development',       desc: 'Modular implementation in Next.js with dynamic data visualization, AI integration and multi-format export.' },
      ],
      results: [
        { value: 'AI',   label: 'Recommendations'    },
        { value: '3x',   label: 'Export formats'     },
        { value: 'OWASP', label: 'Risk standard'     },
      ],
    },
    year:    '2025',
    tags:    [
      { name: 'Next.js',      percentage: 90 },
      { name: 'Tailwind CSS', percentage: 85 },
      { name: 'Figma',        percentage: 80 },
      { name: 'OWASP',        percentage: 70 },
      { name: 'SaaS',         percentage: 75 },
    ],
    process: [
      { num: '01', title: 'Arquitectura de datos', desc: 'Mapeo de todos los tipos de dato (resultados de escaneos, niveles de riesgo, planes de acción, historial) y definición de jerarquía y agrupación.' },
      { num: '02', title: 'Diseño UI',             desc: 'Diseño de componentes para matrices de riesgo, tarjetas de vulnerabilidad y paneles de reporte. Prototipado interactivo en Figma.' },
      { num: '03', title: 'Desarrollo',            desc: 'Implementación modular en Next.js con visualización de datos dinámica, integración de IA y exportación en múltiples formatos.' },
    ],
    results: [
      { value: 'IA',    label: 'Recomendaciones'  },
      { value: '3x',    label: 'Formatos de exportación' },
      { value: 'OWASP', label: 'Estándar de riesgo' },
    ],
    frontImage: '/projects/VulnmasterDashboard - Sitio (1).png',
    image:      '/projects/VulnmasterDashboard - Sitio (1).png',
    gallery: [
      '/projects/VulnmasterDashboard - Sitio (1).png',
      '/projects/VulnmasterDashboard - Sitio (2).png',
      '/projects/VulnmasterDashboard - Sitio (3).png',
      '/projects/VulnmasterDashboard - Sitio (4).png',
      '/projects/VulnmasterDashboard - Informe (1).png',
      '/projects/VulnmasterDashboard - Informe (2).png',
      '/projects/VulnmasterDashboard - Informe (3).png',
      '/projects/VulnmasterDashboard - Informe (4).png',
    ],
    url:        '',
    category:   'Website Design',
  },
  {
    slug: 'tipografia-ii-vignelli',
    title: 'Sistema tipográfico',
    subtitle: 'Puestas en página a partir de fragmentos de Massimo Vignelli',
    client: 'Cátedra Carbone',
    role: 'Diseño Tipográfico',
    description:
      'Trabajo práctico de la materia Tipografía II (Cátedra Carbone, FADU). A partir de un texto de Massimo Vignelli tomé distintos fragmentos y diseñé puestas tipográficas independientes que, sin embargo, pertenecen a un mismo sistema visual: misma paleta (rojo, negro y blanco), misma lógica de retícula y jerarquía, y un tratamiento tipográfico contundente en línea con el pensamiento del propio Vignelli sobre disciplina, significado y atemporalidad en el diseño. El resultado es un conjunto de piezas que se leen por separado pero se reconocen como parte de un mismo lenguaje.',
    en: {
      title:       'Typographic System',
      subtitle:    'Page layouts built from fragments of Massimo Vignelli\'s writing',
      client:      'Carbone Course',
      role:        'Typographic Design',
      description: 'Coursework for Typography II (Carbone course, FADU). Starting from a text by Massimo Vignelli, I took different fragments and designed independent typographic layouts that still belong to a single visual system: the same palette (red, black and white), the same grid logic and hierarchy, and a bold typographic treatment aligned with Vignelli\'s own thinking on discipline, meaning and timelessness in design. The result is a set of pieces that read individually but are recognizable as part of the same language.',
      process: [
        { num: '01', title: 'Text Analysis', desc: 'Reading of Vignelli\'s writing and selection of fragments with strong conceptual weight.' },
        { num: '02', title: 'System Design',  desc: 'Definition of a shared grid, palette and typographic hierarchy to unify every layout.' },
        { num: '03', title: 'Layouts',        desc: 'Design of independent typographic compositions, each built around one fragment.' },
      ],
      results: [
        { value: '1',   label: 'Visual system'    },
        { value: '4',   label: 'Typographic layouts' },
        { value: 'B/N/R', label: 'Color palette'  },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Tipografía',   percentage: 90 },
      { name: 'Retícula',     percentage: 80 },
      { name: 'Illustrator',  percentage: 75 },
      { name: 'Sistema visual', percentage: 70 },
    ],
    process: [
      { num: '01', title: 'Análisis de texto', desc: 'Lectura del texto de Vignelli y selección de fragmentos con peso conceptual.' },
      { num: '02', title: 'Diseño de sistema', desc: 'Definición de una retícula, paleta y jerarquía tipográfica compartidas para unificar las puestas.' },
      { num: '03', title: 'Puestas',           desc: 'Diseño de composiciones tipográficas independientes, cada una construida a partir de un fragmento.' },
    ],
    results: [
      { value: '1',     label: 'Sistema visual'        },
      { value: '4',     label: 'Puestas tipográficas'  },
      { value: 'B/N/R', label: 'Paleta de color'       },
    ],
    frontImage: '/projects/TipoII - TP1/tipo2 - tp1 (7).png',
    image:      '/projects/TipoII - TP1/tipo2 - tp1 (7).png',
    gallery: [
      '/projects/TipoII - TP1/tipo2 - tp1 (1).png',
      '/projects/TipoII - TP1/tipo2 - tp1 (2).png',
      '/projects/TipoII - TP1/tipo2 - tp1 (3).png',
      '/projects/TipoII - TP1/tipo2 - tp1 (4).png',
      '/projects/TipoII - TP1/tipo2 - tp1 (5).png',
      '/projects/TipoII - TP1/tipo2 - tp1 (6).png',
      '/projects/TipoII - TP1/tipo2 - tp1 (7).png',
    ],
    url:        'https://www.instagram.com/p/C7H_CQfvP_W/?img_index=1',
    category:   'University',
  },
  {
    slug: 'tipografia-ii-revista-vignelli',
    title: 'Revista .tip',
    subtitle: 'La entrevista a Massimo Vignelli en 10 páginas',
    client: 'Cátedra Carbone',
    role: 'Diseño Editorial',
    description:
      'Trabajo práctico 2 de Tipografía II (Cátedra Carbone, FADU), continuación directa del TP1. El desafío fue diseñar una revista a partir del contenido de una entrevista a Massimo Vignelli, manteniendo el sistema visual ya definido —paleta roja, negra y blanca, tipografía contundente y jerarquía clara— pero ahora resuelto en un formato editorial de largo aliento: toda la entrevista debía entrar exactamente en 10 páginas. El trabajo puso a prueba el sistema en escala real, exigiendo coherencia de retícula, jerarquía tipográfica y legibilidad a lo largo de toda la publicación, sin perder la identidad construida en el TP1.',
    en: {
      title:       '.tip Magazine',
      subtitle:    'Massimo Vignelli\'s interview fit into exactly 10 pages',
      client:      'Carbone Course',
      role:        'Editorial Design',
      description: 'Practical assignment 2 of Typography II (Carbone course, FADU), a direct continuation of TP1. The challenge was to design a magazine from the content of an interview with Massimo Vignelli, keeping the visual system already defined —red, black and white palette, bold typography and clear hierarchy— but now resolved as a long-form editorial piece: the entire interview had to fit into exactly 10 pages. The project tested the system at real scale, demanding grid consistency, typographic hierarchy and readability throughout the whole publication without losing the identity built in TP1.',
      process: [
        { num: '01', title: 'Content Analysis',  desc: 'Editing and structuring the interview text to define exactly how it would fit into 10 pages.' },
        { num: '02', title: 'Editorial System',  desc: 'Grid, typographic hierarchy and visual continuity with the TP1 system.' },
        { num: '03', title: 'Layout',            desc: 'Page-by-page layout of the 10 spreads, balancing readability and reading rhythm.' },
      ],
      results: [
        { value: '10',  label: 'Pages'            },
        { value: '1',   label: 'Editorial system' },
        { value: 'B/N/R', label: 'Color palette'  },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Diseño Editorial', percentage: 90 },
      { name: 'Maquetación',      percentage: 85 },
      { name: 'Tipografía',       percentage: 85 },
      { name: 'Retícula',         percentage: 80 },
    ],
    process: [
      { num: '01', title: 'Análisis de contenido', desc: 'Edición y estructuración del texto de la entrevista para definir cómo entraría exactamente en 10 páginas.' },
      { num: '02', title: 'Sistema editorial',     desc: 'Retícula, jerarquía tipográfica y continuidad visual con el sistema del TP1.' },
      { num: '03', title: 'Maquetación',           desc: 'Diagramación página a página de las 10 planchas, cuidando la legibilidad y el ritmo de lectura.' },
    ],
    results: [
      { value: '10',    label: 'Páginas'           },
      { value: '1',     label: 'Sistema editorial' },
      { value: 'B/N/R', label: 'Paleta de color'   },
    ],
    frontImage: '/projects/TipoII - TP2/tipo2 - tp2 (1).png',
    image:      '/projects/TipoII - TP2/tipo2 - tp2 (1).png',
    gallery: [
      '/projects/TipoII - TP2/tipo2 - tp2 (1).png',
      '/projects/TipoII - TP2/tipo2 - tp2 (2).png',
      '/projects/TipoII - TP2/tipo2 - tp2 (3).png',
    ],
    url:        '',
    category:   'University',
  },
  {
    slug: 'tipografia-ii-totem-nobel',
    title: 'Interfaz para tótem digital',
    subtitle: 'Prototipo interactivo sobre los Premios Nobel latinoamericanos',
    client: 'Cátedra Carbone',
    role: 'Diseño UX/UI',
    description:
      'Trabajo práctico 6 de Tipografía II (Cátedra Carbone, FADU). La consigna era diseñar en Figma la interfaz de un tótem de digital signage —una pantalla vertical interactiva pensada para espacios públicos— a partir de un tema asignado por la cátedra; en mi caso, los Premios Nobel latinoamericanos. Diseñé un sistema de navegación táctil (inicio, mapa, categorías y fichas individuales) resuelto con una identidad tipográfica y cromática propia, priorizando la lectura a distancia, la jerarquía de la información y una interacción simple pensada para uso público.',
    en: {
      title:       'Digital Signage Totem Interface',
      subtitle:    'Interactive prototype about Latin American Nobel laureates',
      client:      'Carbone Course',
      role:        'UX/UI Design',
      description: 'Practical assignment 6 of Typography II (Carbone course, FADU). The brief was to design in Figma the interface for a digital signage totem —an interactive vertical screen meant for public spaces— based on a topic assigned by the chair; in my case, Latin American Nobel laureates. I designed a touch navigation system (home, map, categories and individual profiles) with its own typographic and color identity, prioritizing readability from a distance, information hierarchy and simple interaction suited for public use.',
      process: [
        { num: '01', title: 'UX Research',   desc: 'Study of digital signage/totem interfaces and public-space interaction patterns.' },
        { num: '02', title: 'UI System',     desc: 'Definition of navigation, typography and color system for touch interaction.' },
        { num: '03', title: 'Prototyping',   desc: 'Interactive prototype in Figma with screen-to-screen navigation flows.' },
      ],
      results: [
        { value: 'Figma', label: 'Interactive prototype' },
        { value: '1',      label: 'Navigation system'    },
        { value: 'UX/UI',  label: 'Public-space design'  },
      ],
    },
    year:    '2024',
    tags:    [
      { name: 'Figma',        percentage: 90 },
      { name: 'UX/UI',        percentage: 85 },
      { name: 'Prototipado',  percentage: 85 },
      { name: 'Tipografía',   percentage: 70 },
    ],
    process: [
      { num: '01', title: 'Investigación UX', desc: 'Estudio de interfaces de digital signage/tótem y patrones de interacción en espacios públicos.' },
      { num: '02', title: 'Sistema UI',        desc: 'Definición de navegación, tipografía y sistema de color para interacción táctil.' },
      { num: '03', title: 'Prototipado',       desc: 'Prototipo interactivo en Figma con flujos de navegación entre pantallas.' },
    ],
    results: [
      { value: 'Figma', label: 'Prototipo interactivo'    },
      { value: '1',     label: 'Sistema de navegación'    },
      { value: 'UX/UI', label: 'Diseño para vía pública'  },
    ],
    frontImage: '/projects/TipoII - TP6/tipo2 - tp6 (1).png',
    image:      '/projects/TipoII - TP6/tipo2 - tp6 (1).png',
    gallery: [
      '/projects/TipoII - TP6/tipo2 - tp6 (1).mp4',
      '/projects/TipoII - TP6/tipo2 - tp6 (2).mp4',
      '/projects/TipoII - TP6/tipo2 - tp6 (1).png',
      '/projects/TipoII - TP6/tipo2 - tp6 (2).png',
      '/projects/TipoII - TP6/tipo2 - tp6 (3).png',
    ],
    url:        '',
    category:   'University',
  },
];

export function getAllProjects() {
  return projects;
}

export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug);
}
